### ISSUE TITLE
Improvement: Gitlab CE

### ISSUE THREAD

**Issue by Duneyr** [GOD-mbh/terraform-eks-env-workshop#6]
Maybe I missed it, but a place for code reviews / pull requests is missing. Shall I take care, or are there more important matters?

Best regards!

**Comment by timurgaleev** [comment]
At the moment we have no other important issues. It will be good if you implement this as well
BR

**Comment by timurgaleev** [comment]
> Maybe I missed it, but a place for code reviews / pull requests is missing. Shall I take care, or are there more important matters?
> 
> Best regards!

At the moment we have no other important issues. It will be good if you implement this as well
BR

**Comment by timurgaleev** [comment]
Yeah, currently I don't have the time to fix all our domain as one.
But in the future it should be as this code 
https://github.com/GOD-mbh/terraform-eks-env-workshop/blob/7d3b7e80088b589103341919e20c7d3bd3b850cf/charts/modules/keycloak/main.tf#L40

**Comment by Duneyr** [comment]
Also lacking time :( 

This is what I have so far:

(Gitlab runners are deactivated for now)

```

provider "kubernetes" {
  #  load_config_file = "false"
  #  depends_on = [kubernetescluster,]
  config_context = "godgitlab"
}

resource "kubernetes_namespace" "gitlab-namespace" {
  metadata {
    name = "gitlab"
  }
}


resource "helm_release" "gitlab" {
  name       = "gitlab"
  namespace  = "gitlab"
  repository = "https://charts.gitlab.io/"
  chart      = "gitlab"
  version    = "4.3.5"


  set {
    name  = "certmanager.install"
    value = false
  }
  set {
    name  = "global.ingress.configureCertmanager"
    value = false
  }
  set {
    name  = "global.hosts.gitlab.name"
// here is the interesting part
    value = kubernetes_service.nginx.load_balancer_ingress[0].hostname
  }
  set {
    name  = "gitlab-runner.install"
    value = false
  }
  set {
    name  = "global.edition"
    value = "ce"
  }
}
```
